services:
  webdev:
    build: ./quicknotes-backend
    env_file:
      - ./quicknotes-backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./quicknotes-backend:/app
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate --no-input &&
             python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:16
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build: ./quicknotes-frontend
    volumes: 
    - ../quicknotes-frontend/src:/app/src
    ports:
      - 5173:5173
    command: sh -c 'npm run dev -- --host 0.0.0.0'

volumes:
  postgres_data: