@baseUrl = http://localhost:8000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg3MjcxMjk2LCJpYXQiOjE3ODcyMjgwOTYsImp0aSI6IjRjYjBjM2FiM2Y5ZjRiZGNhNGRlZmUwYmZjYTViZDMyIiwidXNlcl9pZCI6IjEifQ.UEqRYieufkx_x70g1IcfXRn0-GzCy80tY6TpYwQCw1Y

GET {{baseUrl}}/api/notes
Authorization: Bearer {{token}}

### Register
POST {{baseUrl}}/api/auth/register/
Content-Type: application/json

{
    "username": "Andtan",
    "email": "andtan@tantan.com",
    "password": "password123"
}

### Login
POST {{baseUrl}}/api/auth/login/
Content-Type: application/json

{
    "username": "Andtan",
    "password": "password123"
}

### Refresh Token
POST {{baseUrl}}/api/auth/refresh/
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4OTcxMjkxMCwiaWF0IjoxNzg3MTIwOTEwLCJqdGkiOiIwMjJhYjMwOGZhMTA0ODZkYjI5NDdlZTMyYTY2ZTdjZiIsInVzZXJfaWQiOiIxIn0.0NjqD-CGLYfuZxKdPjVpShQ1eKcVDKnTAkalRpH4kbQ"
}

### Get collections
GET {{baseUrl}}/api/collections
Authorization: Bearer {{token}}

### Get notes
GET {{baseUrl}}/api/notes
Authorization: Bearer {{token}}