@baseUrl = http://localhost:8000

GET http://localhost:8000/api/notes
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg2NDM4NTcwLCJpYXQiOjE3ODY0MzgyNzAsImp0aSI6IjY5NGU1OTc1YWJkNjQ0NGJiOGU2ZDQzYjkwYmI2Njk0IiwidXNlcl9pZCI6IjEifQ.NrmSYUmd9iGQ7-DRw3MLSgH1x92ka1dTBrEJl0RPDek
### Register
POST {{baseUrl}}/api/auth/register/
Content-Type: application/json

{
    "username": "Andtan",
    "email": "andtan@tantan.com",
    "password": "password123"
}

### Login
POST {{baseUrl}}/api/auth/login/
Content-Type: application/json

{
    "username": "Andtan",
    "password": "password123"
}