@baseUrl = http://localhost:8000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg2OTk2MDY0LCJpYXQiOjE3ODY5NTI4NjQsImp0aSI6ImRlMGE1Y2NhNGM5NjQ2ZjU5YTYxN2Y1OTFlNTRhNGQ0IiwidXNlcl9pZCI6IjEifQ.mZKh_ixxUFt0GMR5x6rhflvhGnexX45Iwu7XRJZDKLM

GET {{baseUrl}}/api/notes
Authorization: Bearer {{token}}

### Register
POST {{baseUrl}}/api/auth/register/
Content-Type: application/json

{
    "username": "Andtan",
    "email": "andtan@tantan.com",
    "password": "password123"
}

### Login
POST {{baseUrl}}/api/auth/login/
Content-Type: application/json

{
    "username": "Andtan",
    "password": "password123"
}

### Refresh Token
POST {{baseUrl}}/api/auth/refresh/
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4OTU0NDY2MiwiaWF0IjoxNzg2OTUyNjYyLCJqdGkiOiIwNzgxNTFhMWQ1Zjc0ZGFmODlhODA1ZGE3NTBiMDQ4NCIsInVzZXJfaWQiOiIxIn0.ffNR8RPGsQuJXrbvmgoXGqD5BHhMkDSJzw11ZOgR7p8"
}

### Get collections
GET {{baseUrl}}/api/collections
Authorization: Bearer {{token}}

### Get notes
GET {{baseUrl}}/api/notes
Authorization: Bearer {{token}}